apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amate.fullname" . }}-mysql
  labels:
    app: {{ include "amate.name" . }}
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.amateMysql.service.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: amate-mysql-env
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "amate.fullname" . }}-mysql-pvc