apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrap-summarizer
  namespace: amate
  labels:
    app: scrap-summarizer
spec:
  replicas: 5
  selector:
    matchLabels:
      app: scrap-summarizer
  template:
    metadata:
      labels:
        app: scrap-summarizer
    spec:
      containers:
      - name: scrap-summarizer
        image: ajoumate/scrap_summarizer:latest
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: summarize-bot-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m" 