apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrap-embedder
  namespace: amate
  labels:
    app: scrap-embedder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrap-embedder
  template:
    metadata:
      labels:
        app: scrap-embedder
    spec:
      containers:
      - name: scrap-embedder
        image: ajoumate/scrap_embedder:latest
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: embedding-bot-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m" 