apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    grpc:
      enable: true
      port: 19530
    http:
      enable: true
      port: 19121