apiVersion: v1
kind: Service

metadata:
  name: {{ include "amate.fullname" . }}-fe
  labels:
    {{- include "amate.labels" . | nindent 4 }}
    component: fe

spec:
  type: NodePort
  ports:
    - port: {{ .Values.amateFe.service.deployPort }}
      targetPort: {{ .Values.amateFe.service.port }}
      nodePort: {{ .Values.amateFe.service.deployPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "amate.selectorLabels" . | nindent 4 }}
    component: fe
