apiVersion: v1
kind: Service

metadata:
  name: {{ include "amate.fullname" . }}-ai
  labels:
    {{- include "amate.labels" . | nindent 4 }}
    component: be

spec:
  type: NodePort
  ports:
    - port: {{ .Values.amateAi.service.deployPort }}
      targetPort: {{ .Values.amateAi.service.port }}
      nodePort: {{ .Values.amateAi.service.deployPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "amate.selectorLabels" . | nindent 4 }}
    component: be
