apiVersion: v1
kind: Service
metadata:
  name: {{ include "amate.fullname" . }}-mysql
  labels:
    component: mysql
spec:
  type: NodePort
  ports:
    - port: {{ .Values.amateMysql.service.deployPort }}
      targetPort: {{ .Values.amateMysql.service.port }}
      nodePort: {{ .Values.amateMysql.service.deployPort }}
  selector:
    component: mysql